language: node_js

node_js:
  - "10"
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn
  - yarn run build

script:
  - yarn run test

notifications:
  email:
    on_success: never
